version: 0.0
os: linux
files:
  - source: GloProxSys.MDPApp.Concierge/build_output
    destination: /home/ubuntu/GloProxSys.MDPApp.Concierge
  - source: scripts/virtualhost.conf
    destination: /home/ubuntu/GloProxSys.MDPApp.Concierge
  - source: scripts/kestrel-GloProxSys.MDPApp.Concierge.service
    destination: /etc/systemd/system/
hooks:
  ApplicationStop:
    - location: scripts/stop_service
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/remove_application
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dotnetcore
      timeout: 500
      runas: root

    - location: scripts/install_httpd
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/start_service
      timeout: 300
      runas: root
